spring:
  main:
    web-application-type: servlet
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/dogworld
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  mvc:
    static-path-pattern: /static/**
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

cloudinary:
  cloud_name: dbfeg6elz
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

